### PR TITLE
add string color prompt helper

### PR DESCRIPTION
**Pull request by vityou**
Feel free to change anything if you want.  Not really sure about names, they could be better.

### CODE REVIEW

**Comment by vityou** [comment]
It looks like supporting `color%` would add the `draw-lib` dependency, so maybe `color%` shouldn't be supported?

**Comment by vityou** [comment]
Ok, well I made it so that it would accept any object with red, green, and blue methods, so it doesn't require draw-lib anymore.  If the user gives is their own `color%` object it will work.

**Comment by willghatch** [comment]
I think you want children to not inherit if their argument is given explicitly.  Eg:

```
(displayln
   (styled-struct->string
    (create-styled-struct
     #:underlined? #t
     "underlined "
     (create-styled-struct
      #:underlined? #f
      "not underlined")
     " underlined")))
```

The "not underlined" part is still underlined.  This leads me to think that each styled-struct should probably have all attributes to set explicitly stored and reset before setting anything.  I'm somewhat sorry to say that the easiest way I can currently think of to make this work is to use a macro and either parameters (IE by having the macro `parameterize` parameters to get defaults for unspecified values and controlling evaluation order of sub-forms to make sure they happen within the body of the `parameterize` form) or syntax-parameters (which would be fairly similar).  Of course, if you have any other way you want to do it, that's fine too -- those are just what immediately jump to my mind.

Also, I would suggest the names be more consistent -- maybe `create-styled-string` instead of `create-colored-string`.

**Comment by vityou** [comment]
It looks like there are escape sequences that turn the features off, but some aren't supported.  I suppose I could store the struct's style as a hash and have the struct->string take care of it.  Although I'll have to find a way to take care of the custom and I commands the user adds.

**Comment by vityou** [comment]
I'm thinking passing `(void)` to something like `#:fg` could mean keep whatever outer struct had, `#f` means get rid of what outer struct had, and anything else would override whatever outer struct had.

**Comment by vityou** [comment]
Ok, there we go.  Sub-structs can override individual styles.

**Comment by willghatch** [comment]
Great.  For a default argument I suggest a non-exported struct or an uninterned/gensymed symbol.  That way you can't ever have it passed in by something from the outside.  Eg. someone could be using `void` as a truth-y value.

**Pull request merged**
